version: "3.1"

services:
  mariadb-app:
    image: khagu/tp-docker-mariadb:1.0.0
    networks:
      - mariadbnet
    volumes:
      - database:/var/lib/mysql
  
  python-app:
    image: khagu/tp-docker-python:1.0.0
    stdin_open: true # docker run -i
    tty: true        # docker run -t
    networks:
      - mariadbnet
    volumes:
      - /appli:/appli
    environment:
      DB_USER: toto
      DB_PASSWORD: test123
      DB_HOST: mariadb-app
      DB_PORT: 3306
      DB_NAME: parc_informatique

volumes:
  database:
  appli:

networks:
  mariadbnet: