version: "3.1"

services:
  mariadb-app:
    image: mariadb-app
    networks:
      - mariadbnet
    volumes:
      - /database:/database
  
  python-app:
    image: python-app
    stdin_open: true # docker run -i
    tty: true        # docker run -t
    networks:
      - mariadbnet
    volumes:
      - /appli:/appli
    environment:
      DB_USER: toto
      DB_PASSWORD: test123
      DB_HOST: mariadb-app
      DB_PORT: 3306
      DB_NAME: parc_informatique

volumes:
  database:
  appli:

networks:
  mariadbnet: